name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and publish to github packages
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag docker.pkg.github.com/sjnyos/gitact-nodejs-adv:${VERSION}
        docker login docker.pkg.github.com --username sjnyos --password Sur@j123456
        docekr push docker.pkg.github.com/sjnyos/gitact-nodejs-adv:${VERSION}
      
